FROM node:18-bullseye-slim

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

EXPOSE 3000
EXPOSE 9229

COPY package.json yarn.lock ./
RUN apt-get update && apt-get install -y --no-install-recommends apt-transport-https ca-certificates git gnupg gettext python3 make g++
RUN update-ca-certificates
RUN yarn install
ENV PATH /app/node_modules/.bin:$PATH


WORKDIR /app
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["npm", "run", "docker-start"]
