FROM node:18-bullseye-slim

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

EXPOSE 3000
EXPOSE 9229

COPY package.json yarn.lock ./
RUN yarn install
#install pm2 and rerun onchange?
CMD ["node", "./test/server-test.js"]