FROM node:20-bookworm-slim

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

EXPOSE 8080
EXPOSE 9229

RUN npm install browser-refresh -g
COPY package.json yarn.lock ./
RUN apt-get update && apt-get install -y --no-install-recommends apt-transport-https ca-certificates git gnupg
RUN update-ca-certificates
RUN yarn install
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app

CMD ["npm", "run", "dev"]